application: muntjac-demo
version: DEBUG-VERSION
runtime: python
api_version: 1
threadsafe: false

handlers:
- url: /cleanup_sessions
  script: muntjac/demo/cleanup_sessions.py
  login: admin

- url: /VAADIN
  static_dir: VAADIN

- url: /(hello|calc|address|tunes|sampler|colorpicker|codemirror|googlemaps).*
  script: muntjac/demo/gae.py

- url: /
  static_files: muntjac/public/index.html
  upload: muntjac/public/index.html

- url: /
  static_dir: muntjac/public

builtins:
- appstats: on

skip_files: muntjac/public/VAADIN/.*
