# @MUNTJAC_COPYRIGHT@
# @MUNTJAC_LICENSE@


class ApplicationConnection(object):

    # This indicates the whole page is generated by us (not embedded)
    GENERATED_BODY_CLASSNAME = 'v-generated-body'

    UIDL_SECURITY_TOKEN_ID = 'Vaadin-Security-Key'

    PARAM_UNLOADBURST = 'onunloadburst'