# -*- coding: utf-8 -*-
# @ITMillApache2LicenseForJavaFiles@


class VAcceptCriterionFactory(object):
    """Generated by {@link AcceptCriteriaFactoryGenerator}"""

    def get(self, name):
        pass
